export const LOAD_TREATMENTS_SUCCESS = 'LOAD_TREATMENTS_SUCCESS';

export const CREATE_TREATMENT_SUCCESS = 'CREATE_TREATMENT_SUCCESS';
export const UPDATE_TREATMENT_SUCCESS = 'UPDATE_TREATMENT_SUCCESS';
