export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_TREATMENTS_SUCCESS = 'LOAD_TREATMENTS_SUCCESS';
export const CREATE_TREATMENT_SUCCESS = 'CREATE_TREATMENT_SUCCESS';
export const UPDATE_TREATMENT_SUCCESS = 'UPDATE_TREATMENT_SUCCESS';
